name: QuestBot Deployment

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  IMAGE_TAG: ${{ GITEA.REF == 'refs/heads/main' && 'latest' || 'develop' }}

jobs:
  Build:
    runs-on: ubuntu-latest
    needs: [ Lint ]
    if: GITEA.REF == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: git.nke.team:8443
          username: ${{ GITEA.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: git.nke.team:8443/${{ GITEA.REPOSITORY_OWNER }}/${{ GITEA.EVENT.REPOSITORY.NAME }}:${{ env.IMAGE_TAG }}

  Deploy:
    runs-on: ubuntu-latest
    needs: [ Build ]
    if: GITEA.REF == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Выполнение развертывания в production среду
        uses: dawidd6/action-ansible-playbook@v2
        with:
          directory: ./ansible
          playbook: deploy.yml

          key: ${{ secrets.CAREER_BOT_KEY }}

          inventory: |
            [all]
            server ansible_host=${{ SECRETS.CAREER_BOT_HOST }} ansible_port=${{ SECRETS.CAREER_BOT_PORT }} ansible_user=${{ SECRETS.CAREER_BOT_USER }}
